### ISSUE TITLE
Mismatched .dbf and .shp record count -- possible data loss.

### ISSUE THREAD

**Issue by jherjati** [mapbox/shp-write#106]
Looks like record indexes in shape files need to start at 1 not 0. As mentioned here :

https://github.com/mapbox/shp-write/pull/69

Really hope this got merged into main branch and released.
Thank you, appreciate the useful tool !

**Comment by sheindel** [comment]
This should be fixed as of the latest change. Are you using the new package URL? We had to change package names in NPM from `shp-write` to `@mapbox/shp-write`

**Comment by jherjati** [comment]
No, I still face this problem in the newest version, @mapbox/shp-write, might be because the previous fix only merged into maintenance branch?

**Comment by jherjati** [comment]
Thanks for your response.

Whoever face this issue with download API, what's work with me is changing my code to use zip API.

But at first I couldn't make it works because I thought the returned type is ArrayBuffer so I convert it first to Blob and it failed.

Then I realized that I can make the returned value directly in Blob type using options, then just make the download URL, it works 👌
